version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch-node1
    environment:
      - node.name=node-1
      - cluster.name=my-elasticsearch-cluster
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/logs
      - network.host=0.0.0.0
      - discovery.seed_hosts=node-1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    restart: unless-stopped

networks:
  elastic:
    driver: bridge

volumes:
  es-data:
    driver: local
